### ISSUE TITLE
Accessories are not framed.

### ISSUE THREAD

**Issue by DBdeepsleeper** [Essyer/PoETiS#11]
hi.

Accessories are not framed.

Version 1.9 works fine.

It seems to be a bug, so please report it.

![image](https://user-images.githubusercontent.com/68507771/153760173-ae8c9688-724a-4402-80bf-9bf30bc006a6.png)

**Comment by Essyer** [comment]
Hello,
I'm not sure why it happens, I just tested it again and accessories were working fine https://i.ibb.co/fGsgwWc/test.jpg
If you contact me on discord (Skaile#9466) I could borrow content of your stash to debug this issue. You can also try to remove items that may cause problems (although the should not) like invitations or uniques.

**Comment by Essyer** [comment]
We've tried few things including me using @DBdeepsleeper account name and session and it seems to be some environmental issue I cannot solve.

**Comment by Essyer** [comment]
@DBdeepsleeper I think I found out what was the issue. I did not update mods.xml file after the update, that's why a lot of items were not detected. It's fixed in recent release.

**Comment by DBdeepsleeper** [comment]
Thank you.
Let's do it in version 3.19.
