### ISSUE TITLE
Failed to execute script, Mainwidget -Error

### ISSUE THREAD

**Issue by AlitheD** [Essyer/PoETiS#2]
I am getting this error when I run executable.
I ran the debugger and here is the message 

PS D:\Desktop\Path of Exile related\PoETiS_1.2_debug> .\PoETiS_debug.exe
Traceback (most recent call last):
  File "MainWidget.py", line 4, in <module>
ImportError: DLL load failed while importing QtCore: The specified module could not be found.
[8572] Failed to execute script MainWidget
![bug](https://user-images.githubusercontent.com/22340400/84589761-84a50e80-ae39-11ea-9d64-a336116dfe7d.png)

**Comment by Essyer** [comment]
I just updated debug version in 1.2, could you try to download and run it again? This time I added specified path to the building procedure, described in the last comment of [this](https://www.reddit.com/r/learnpython/comments/58sta7/error_when_trying_to_package_a_pyqt5_app_using/) post.

**Comment by AlitheD** [comment]
I have downloaded 1.2 debug version again and run it in powershell. 
the error message is now:

```
PS D:\Desktop\Path of Exile related\PoETiS_1.2_debug> .\PoETiS_debug.exe
Traceback (most recent call last):
  File "MainWidget.py", line 4, in <module>
ImportError: DLL load failed while importing QtCore: The specified module could not be found.
[8080] Failed to execute script MainWidget
```

**Comment by Essyer** [comment]
So it did not help... It doesn't have any sense, why only on specific computers it's not working. Would you be able to install PyQt from requirements.txt and test again?

**Comment by AlitheD** [comment]
I have anocanda3, which includes PyQt too. I have tried to run your latest release, yet got the same error. Then I tried to run the debug version and got  
`PS D:\Desktop\Path of Exile related\PoETiS_1.2_debug> .\PoETiS_debug.exe
Traceback (most recent call last):
  File "MainWidget.py", line 4, in <module>
ImportError: DLL load failed while importing QtCore: The specified module could not be found.
[9476] Failed to execute script MainWidget`

**Comment by Essyer** [comment]
Check output of command "pip freeze" in Windows command line. If you have PyQt5 with version specified in requirements.txt or newer then you can install other required modules and run the tool from sources - just download them in ZIP file and run MainWidget.py after extraction. If you have older version of PyQt, you will need to find some workaround. Let me know if you find solution, maybe someone else will need it as well.
